//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesafioT.Infra.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesafioT.Infra.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{
        ///&quot;voo&quot;: &quot;P243B976&quot;,
        ///&quot;origem&quot;: &quot;BSB&quot;,
        ///&quot;destino&quot;: &quot;VCP&quot;,
        ///&quot;data_saida&quot;: &quot;2019-02-10&quot;,
        ///&quot;saida&quot;: &quot;06:40&quot;,
        ///&quot;chegada&quot;: &quot;19:40&quot;,
        ///&quot;valor&quot;: 948.46
        ///},
        ///{
        ///&quot;voo&quot;: &quot;U264B986&quot;,
        ///&quot;origem&quot;: &quot;BSB&quot;,
        ///&quot;destino&quot;: &quot;AJU&quot;,
        ///&quot;data_saida&quot;: &quot;2019-02-10&quot;,
        ///&quot;saida&quot;: &quot;08:00&quot;,
        ///&quot;chegada&quot;: &quot;15:40&quot;,
        ///&quot;valor&quot;: 745.58
        ///},
        ///{
        ///&quot;voo&quot;: &quot;N207B980&quot;,
        ///&quot;origem&quot;: &quot;BSB&quot;,
        ///&quot;destino&quot;: &quot;FLN&quot;,
        ///&quot;data_saida&quot;: &quot;2019-02-10&quot;,
        ///&quot;saida&quot;: &quot;09:00&quot;,
        ///&quot;chegada&quot;: &quot;19:20&quot;,
        ///&quot;valor&quot;: 1347.21
        ///},
        ///{
        ///&quot;voo&quot;: &quot;X282B992&quot;,
        ///&quot;origem&quot;: &quot;BSB&quot;,
        ///&quot;destino&quot;: &quot;VIX&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _99planes {
            get {
                return ResourceManager.GetString("_99planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;nome&quot;: &quot;Aeroporto Internacional Juscelino Kubitschek&quot;,
        ///    &quot;aeroporto&quot;: &quot;BSB&quot;,
        ///    &quot;cidade&quot;: &quot;Brasília&quot;
        ///  },
        ///  {
        ///    &quot;nome&quot;: &quot;Aeroporto Eurico de Aguiar Salles&quot;,
        ///    &quot;aeroporto&quot;: &quot;VIX&quot;,
        ///    &quot;cidade&quot;: &quot;Vitória&quot;
        ///  },
        ///  {
        ///    &quot;nome&quot;: &quot;Aeroporto Internacional Zumbi dos Palmares&quot;,
        ///    &quot;aeroporto&quot;: &quot;MCZ&quot;,
        ///    &quot;cidade&quot;: &quot;Maceió&quot;
        ///  },
        ///  {
        ///    &quot;nome&quot;: &quot;Aeroporto Internacional de Belém de Cans&quot;,
        ///    &quot;aeroporto&quot;: &quot;BEL&quot;,
        ///    &quot;cidade&quot;: &quot;Belém&quot;
        ///  },
        ///  {
        ///    &quot;nome&quot;: &quot;Aeroporto Internaciona [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string airports {
            get {
                return ResourceManager.GetString("airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numero_voo,aeroporto_origem,aeroporto_destino,data,horario_saida,horario_chegada,preco
        ///B13F30,BSB,FLN,2019-02-10,19:00,23:30,369.19
        ///B77M69,BSB,MCZ,2019-02-10,20:00,23:00,413.13
        ///B16V27,BSB,VCP,2019-02-10,07:00,17:00,1317.50
        ///B56P61,BSB,PMW,2019-02-10,19:30,20:30,131.21
        ///V85A47,VIX,AJU,2019-02-10,18:30,22:00,340.67
        ///V96P97,VIX,PLU,2019-02-10,16:00,18:00,269.17
        ///V51M71,VIX,MCZ,2019-02-10,14:00,14:30,48.73
        ///V27B42,VIX,BSB,2019-02-10,12:30,15:00,298.13
        ///M88B16,MCZ,BSB,2019-02-10,14:00,18:00,489.83
        ///M18P21,MCZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uberair {
            get {
                return ResourceManager.GetString("uberair", resourceCulture);
            }
        }
    }
}
